name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
     - name: Check the deloyed service URL
       uses: jtalk/url-health-check-action@v4
       with:
        url: https://full-stack-open-pokedex-muddy-night-4006.fly.dev
        follow-redirect: true
        max-attempts: 3
        retry-delay: 5s
        retry-all: false